### ISSUE TITLE
OSDownloads is not supporting overrides?

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/OSDownloads#125]
We had a report that OSDownloads doesn't support overrides

**Comment by andergmartins** [comment]
Yes, it supports template overrides. I just confirmed for the frontend views and module. The unique issue I saw was a limited support for layouts in the module, but just fixed.

@stevejburge , do you have the link for the post/ticket? I will need more details to check the issue the user is facing.

**Comment by stevejburge** [comment]
This was reported by an end-user. I'll see if they have more details, but otherwise we can close
