### ISSUE TITLE
Choose order of the files inside category

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSDownloads#140]
Order by order, date, name, id
asc, desc

**Comment by htmgarcia** [comment]
https://www.alledia.com/forum/osdownloads/42/

**Comment by andergmartins** [comment]
This is a great idea, but will not be available on this week's release. Probably on the next one.

**Comment by htmgarcia** [comment]
Thanks @andergmartins !

**Comment by htmgarcia** [comment]
@andergmartins is there something I can help you to prioritize this one? 
The user replied again about this feature: https://www.alledia.com/forum/osdownloads/44/#303

**Comment by nicksavov** [comment]
One more:
https://secure.helpscout.net/conversation/84954836/12261/

**Comment by ihuibregtse** [comment]
Hello, has anything happened as yet regarding being able to change the order of the files? Maybe a workaround?
I was going to leave a message on the Alledia forum, but I cannot find a way to regisiter?
Best,
Ineke

**Comment by drocksvold** [comment]
Another vote for this feature...
Thanks for the hard work.

**Comment by htmgarcia** [comment]
Another user requested this feature: https://www.alledia.com/forum/osdownloads/115/

**Comment by raramuridesign** [comment]
+1 for this request.
Could you also extend this to the module so we can sort by 

Order by order, date, name
asc, desc

**Comment by htmgarcia** [comment]
A new request: https://www.alledia.com/forum/osdownloads/232-most-recent-first/

**Comment by htmgarcia** [comment]
Thanks @andergmartins !
