### ISSUE TITLE
Sort in backend

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSDownloads#142]
[feedback]When clicking on the ordering column in the files view (in admin-OSDownloads) nothing happens, meaning I cant change the order of the downloads in my front end. It Works under the categories and on every other list view in my site.[/feedback]
https://www.alledia.com/forum/osdownloads/44/

**Comment by htmgarcia** [comment]
Improvement already requested from https://github.com/OSTraining/OSDownloads/issues/140
Hopefully will be available in the next release.
