### ISSUE TITLE
Fatal error: Cannot redeclare class JViewLegacy

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/OSDownloads#145]
Joomla 3.x

https://www.alledia.com/forum/osdownloads/46/

> Fatal error: Cannot redeclare class JViewLegacy in /libraries/legacy/view/legacy.php on line 812

User implemented it's own solution: https://www.alledia.com/forum/osdownloads/46/reply/#247

**Comment by nicksavov** [comment]
One more
https://www.alledia.com/forum/osdownloads/164

**Comment by nicksavov** [comment]
Fixes https://github.com/OSTraining/OSDownloads/commit/9c9baf73435aa684ed4e3bf6c3c4011efec48db2
