### ISSUE TITLE
Modal opened by default?

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSDownloads#156]
@andergmartins , when an admin creates an OSDownloads menu item that goes to a single file, is it possible to display the modal automatically.

So for example, the admin can give a URL like www.example.org/pdf1?task=routedownload&tmpl=component&id=1 and it would go to that menu item with the modal opened.

**Comment by andergmartins** [comment]
Hey Nick. 

Yes, I think that is possible, and probably fits better this way: #157

**Comment by nicksavov** [comment]
Sounds good! Let's continue in #157
