### ISSUE TITLE
[module] multiple modules in content not showing correct downloads

### ISSUE THREAD

**Issue by raramuridesign** [OSTraining/OSDownloads#169]
How to emulate
Add multiple modules on the same page
Make sure each module is set to show downloads from different categories

When you load the page, it will only show the downloads from the module in position 1, or loading first.

Please can you let us know if this is a bug.
Matthew

issue here
[link removed]

Using latest version of OSDOWNLOADS
This has been tested on j.3.4.x and 2.5.x

**Comment by raramuridesign** [comment]
Hi Team
any follow up on this
Matthew

**Comment by htmgarcia** [comment]
Hi @raramuridesign ,
thanks for sharing this valuable feedback!

I was able to reproduce the issue. 
In my test, I created two OSDownloads modules pointing each to a different category.
In the end result, both modules display the same content.

We are working to get it fixed.

**Comment by raramuridesign** [comment]
Thanks 
looking forward to the update. Any idea on an ETA and will you update here when done ?

**Comment by htmgarcia** [comment]
We will try to add in the next release.

**Comment by raramuridesign** [comment]
Thanks.

**Comment by raramuridesign** [comment]
Hi 
I see 1.3.3 is out, did this get added
Matthew

**Comment by nicksavov** [comment]
Hi Matthew,

Unfortunately, this wasn't added to v1.3.3 as it was a quick release for an issue that was occurring for many users. No other fixes were released with it.

This issue is still on the radar for the next big bug-fix release.

**Comment by raramuridesign** [comment]
Thanks Nick,
ETAon bug fix ?

**Comment by raramuridesign** [comment]
Hey guys any update on this ?

**Comment by raramuridesign** [comment]
Hey guys any update on this ?

**Comment by raramuridesign** [comment]
Thanks. Tested beta, looks like its working

**Comment by nicksavov** [comment]
Thanks for testing, Matthew! Cheers

**Comment by htmgarcia** [comment]
Thank you @andergmartins !
