### ISSUE TITLE
[request] add support for campaign monitor

### ISSUE THREAD

**Issue by raramuridesign** [OSTraining/OSDownloads#171]
Please add support for campaign monitor.

**Comment by nicksavov** [comment]
Hi Matthew,

Great suggestion! Campaign Monitor is new to me, but it looks interesting. Unfortunately, unless we get a lot of requests for it, we're unlikely to add it without a sponsorship for its development.

If you'd like to sponsor the development of it, it will probably be around $250 for us to get it added quickly. We can have it added within about a week after payment, like we did for the Constant Contact feature:
https://www.alledia.com/forum/osdownloads/98/

Let us know if you have any questions and we'll be glad to answer.

**Comment by raramuridesign** [comment]
Thanks.
for now its all ok.

**Comment by nicksavov** [comment]
Cheers Matthew
