### ISSUE TITLE
[request] add support for content plugin

### ISSUE THREAD

**Issue by raramuridesign** [OSTraining/OSDownloads#172]
Add support for content plugin which works in K2 and normal content

example

{osd 1}

where 1 is the ID of the download file.

**Comment by nicksavov** [comment]
Hi Matthew,

Thanks for the feedback!

OSDownloads Pro has that feature. Please check out the "OSDownload in your articles" section in the documentation at https://www.alledia.com/docs/osdownloads/pro-features/

It should work in K2 as well.

**Comment by raramuridesign** [comment]
Thanks Nick.
Has this been tested on K2 ?

**Comment by nicksavov** [comment]
No, since don't use K2 ourselves, but theoretically K2 should be triggering for content plugins as well and it should work in there too.

Let us know if you have any issues though

**Comment by raramuridesign** [comment]
K2 Works.

**Comment by nicksavov** [comment]
Great, glad to hear that, Matthew! :)

Cheers
