### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by patricmutwiri** [OSTraining/OSDownloads#176]
Sql Injection risk on views layout ie. Item. 
![injection](https://cloud.githubusercontent.com/assets/7590159/8645926/5b12f434-2954-11e5-96bc-42f134bb87f7.JPG)

I'll Submit a fix though.

**Comment by stevejburge** [comment]
Thanks @patricmutwiri We appreciate those fixes and we'll look at them today.

**Comment by billtomczak** [comment]
Closed several problems with input sanitization in 97fd82c507c97572e169deac1ab22d4429397547

**Comment by nicksavov** [comment]
Hi Patrick,

Thanks so much for reporting the issues! We've released a new version with the fixes:
https://github.com/OSTraining/OSDownloads/releases/tag/v1.3.4

**Comment by patricmutwiri** [comment]
welcome @nicksavov  I feel humbled .

**Comment by billtomczak** [comment]
Also incorporated @patricmutwiri's patches: decf2dad72f435f8eaec1f02f46cd9e8e58de17e, af42822ba1fd94592ab2b56cf731dde47a928e8f

**Comment by patricmutwiri** [comment]
Again, Thanks... @billtomczak
