### ISSUE TITLE
[module] - sort by most recent files

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSDownloads#180]
Feedback:
> we have a project where the client needs the module to list the files by most recent
www.fairmont.co.za/news/fairmont-focus.html
Is it possible to make tweak in the code, if so please could you add for us.

https://www.alledia.com/forum/osdownloads/229-module-ordering-modules-by-most-recent/#1355

**Comment by htmgarcia** [comment]
A new request to change the ordering, this one is for the component: https://www.alledia.com/forum/osdownloads/232-most-recent-first/

**Comment by raramuridesign** [comment]
;-) thanks...
when will the pro version be available?

**Comment by nicksavov** [comment]
Thanks for your patience, Matthew! It's available now. Please download
