### ISSUE TITLE
Fatal error: Call to undefined method OsDownloadsTableEmail::addToMailchimpList()

### ISSUE THREAD

**Issue by andergmartins** [OSTraining/OSDownloads#205]
Fatal error: Call to undefined method OsDownloadsTableEmail::addToMailchimpList() in administrator/components/com_osdownloads/library/Free/Joomla/Controller/Site.php on line 54

@nicksavov
@corywebb

Ref https://github.com/OSTraining/AllediaFramework/issues/14

**Comment by nicksavov** [comment]
Ref:
https://secure.helpscout.net/conversation/172406639/16696/?folderId=390278

**Comment by nicksavov** [comment]
btw, even though the error is in OSDownloads, it might actually be related to the framework. It was the the same error before and https://github.com/OSTraining/AllediaFramework/commit/af14bfa96f06ecbc26c9d08637cfa8ce6de37f3d fixed it.

**Comment by andergmartins** [comment]
AH, thanks, good catch. Yeah, I see the lack of escaped backslashes in a bunch of places in OSDownloads. Thanks. Let me try that

**Comment by andergmartins** [comment]
Ok, moving back to the Library repo :) Sorry
